### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint 1. Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "nickname": "Mark",
    "email": "marcio@email.com",
    "password": "abc123"
}

### Endpoint 2. Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "marcio@email.com",
    "password": "abc123"
}

### Endpoint 3. Create new recipe (protected)
POST http://localhost:3003/recipes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4
Content-Type: application/json

{
    "title": "Bolo de cenoura",
    "description": "Bolo de cenoura com deliciosa calda de chocalate. Receita ideal para acompanhar um café no fim de tarde."
}

### Endpoint 4. Edit recipe (protected)
PUT http://localhost:3003/recipes/5567d209-d4bb-426d-8fe9-5f2fb8ddca0b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4
Content-Type: application/json

{
    "title": "Lasanha Vegetariana",
    "description": "Lasanha vegetariana saborosa. Preparada exclusivamente com insumos orgânicos."
}

### Endpoint 5. Delete recipe (protected)
DELETE http://localhost:3003/recipes/cb05da0b-2287-4cf6-beef-5b3e46b9e3f5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4

### Endpoint 6. Get all recipes (protected)
GET http://localhost:3003/recipes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4

### Endpoint Get all users (protected)
GET http://localhost:3003/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4

### Endpoint 7. Delete user (protected)
DELETE http://localhost:3003/users/249d0ab3-2852-4245-beb3-2bd2d4919929
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0OWQwYWIzLTI4NTItNDI0NS1iZWIzLTJiZDJkNDkxOTkyOSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk5MDg4OTcsImV4cCI6MTY2MDA4MTY5N30.GFmvMIs7I7FTtwE4mE16y72aHhvEc8224VUcYh40EV4