### Endpoint de teste
GET http://localhost:3003/ping


### Signup
POST http://localhost:3003/signup
Content-Type: application/json

{
    "nickname": "marcio",
    "email": "marcio1@email.com",
    "password": "marcio123"
}

### Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "marcio@email.com",
    "password": "marcio123"
}

### Get all users (protected)
GET http://localhost:3003/users?q=yuzodev
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhNDI5MzZjLTJkMTYtNDc1Yi1hNzVkLTEyMmMwOTNjOTcxOSIsImlhdCI6MTY1OTM5MTI1MywiZXhwIjoxNjU5NDc3NjUzfQ.oNeZJ9kmp65_5rqyUZmdRcqTJDLEXxNgYKLSOvWPpBM

### Update user information (protected)
PUT http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhNDI5MzZjLTJkMTYtNDc1Yi1hNzVkLTEyMmMwOTNjOTcxOSIsImlhdCI6MTY1OTM5MTI1MywiZXhwIjoxNjU5NDc3NjUzfQ.oNeZJ9kmp65_5rqyUZmdRcqTJDLEXxNgYKLSOvWPpBM
Content-Type: application/json

{
    "nickname": "mark"
}

### Delete user (protected)
DELETE http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhNDI5MzZjLTJkMTYtNDc1Yi1hNzVkLTEyMmMwOTNjOTcxOSIsImlhdCI6MTY1OTM5MTI1MywiZXhwIjoxNjU5NDc3NjUzfQ.oNeZJ9kmp65_5rqyUZmdRcqTJDLEXxNgYKLSOvWPpBM
Content-Type: application/json

{
    "id": "58c903e8-9c43-47d3-b10a-2d6ae0ce8079"
}
