### Endpoint teste
GET http://localhost:3003/ping

### Endpoint signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Márcio",
    "email": "marcio@email.com",
    "password": "123456"
}

### Endpoint login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "bananinha"
}

### Endpoint create show
POST http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDkzODI0MywiZXhwIjoxNjYxMTExMDQzfQ.Rzz0YLrQV16PMTEQJkKbmDj2WoenqfEbRA6XN5oB2ao
Content-Type: application/json

{
    "band": "Red Hot Chili Peppers",
    "startsAt": "2022/12/13"
}

### Endpoint get shows
GET http://localhost:3003/shows

### Endpoint add ticket booking
POST http://localhost:3003/shows/tickets/201
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg0ODk5MCwiZXhwIjoxNjYxMDIxNzkwfQ.5G3O6oEmfs8RfOa_jYpkxDL2l7Ph8UVk_eYbarpnVyw

### Endpoint remove ticket booking
DELETE http://localhost:3003/shows/tickets/201
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDg0OTIyMCwiZXhwIjoxNjYxMDIyMDIwfQ.wq72wucrJoXNwcZ7Y8avLGsT4KycMoHw_V4bmCNc2rs